baseURL = 'https://kuanchristensen.com'
languageCode = 'de-DE'
theme = 'coming-soon'

[params]
  title = 'Kuan / Christensen Klavierduo'
  description = "Bitte in Kürze noch einmal vorbeischauen"
  FAVICON = ""
  message = "Baldige Eröffnung..."
  RELEASE = "Feb 14, 2024 14:00" 
  background = ""
